# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BPTLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BPTLogin
  
   pod 'Alamofire', '~> 4.8.2'
   pod 'SwiftyJSON', '~> 5.0.0'
   
  target 'BPTLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BPTLoginUITests' do
    # Pods for testing
  end

end
